### ISSUE TITLE
sql文件呢？？

### ISSUE THREAD

**Issue by 1617295759** [Sauceggplant/dm#1]

**Comment by zhaozixing** [comment]
main/src/main/resources/init.sql

**Comment by zhaozixing** [comment]
Jpa 可以自动建表

**Comment by 1617295759** [comment]
谢谢作者的回复。还有个问题，是怎么实现的sqk查询呢？没有看到repository包里接口的实现和sql语句。

**Comment by zhaozixing** [comment]
jpa可以理解为基于规范的规范；只写接口不用写实现类，自动完成增删改查

**Comment by zhaozixing** [comment]
Spring boot data jpa 持久化本质还是hibernate
